[package]
name = "role-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
sqlx = { version = "0.8.2", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1.42.0", features = ["full"] }
tracing = "0.1.41"
twilight-gateway = "0.15.4"
